### PR TITLE
fix(main): include message content

### PR DESCRIPTION
**Pull request by ooliver1**
- Update `disnake` to latest in `poetry.lock`.
- Include the `message_content` intent in `__main__.py.

### CODE REVIEW

**Comment by onerandomusername** [comment]
...why is this occurring anyways?

**Comment by ooliver1** [comment]
Because there is no message content intent enabled? It did not exist at the time using that disnake version.

**Comment by onerandomusername** [comment]
It doesn't need to be, that disnake version isn't on api v10 and therefore doesn't require the intent. Somehow, this is discord's fault, as running the same code (but on a new gateway session) I receive the message content when using disnake 2.3.0

**Comment by onerandomusername** [comment]
This is no longer an issue.

**Pull request closed without merging**
